//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Record_Id { get; set; }
        public string CartId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ItemList ItemList { get; set; }
    }
}
