//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantDBEntities : DbContext
    {
        public RestaurantDBEntities()
            : base("name=RestaurantDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemList> ItemLists { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart1> Carts1 { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GuestDetail> GuestDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<LoginModel> LoginModels { get; set; }
    }
}
